// IMPORTS
// -----------------------------
import * as utils from "../utils/utils.js";
import * as store from "../utils/store.utils.js";

// VARIABLES AND CONSTANTS
// -----------------------------
let timerInterval = null;

// FUNCTIONS
// -----------------------------

// FUNCTION Set timer
export const setUpTimer = (action) => {
  // Set timer variable
  let timer = store.timerDuration;

  // If clear interval is false, start the timer
  if (action === "start") {
    // Set interval of one second (1000ms)
    timerInterval = setInterval(() => {
      // Decrement timer every second
      timer--;
      // Display the time generated by the timer
      store.targetYourTime.textContent = utils.transformInMinutesSeconds(timer);
      store.updateTimeRemaining(timer);
      if (timer < 1) {
        // Display Lose Message with adding class to loser message
        let loserMessage = document.getElementById("loserMessage");
        loserMessage.classList.remove("closeMessage");
        setTimeout(() => {
          loserMessage.classList.add("revealMessage");
        }, 0);
        // Clear Interval to stop the loop
        clearInterval(timerInterval);
      }
    }, 1000);

    // Else, if clear the interval is true, reset the timer
  } else if (action === "clear") {
    // Stop looping for timer
    clearInterval(timerInterval);
    // Display the timer as reset
    store.targetYourTime.textContent = utils.transformInMinutesSeconds(timer);
    store.updateTimeRemaining(timer);
  } else if (action === "stop") {
    // Stop looping for timer
    clearInterval(timerInterval);
  }
};

// FUNCTION Start timer when first click on image
export const startTimer = () => {
  // Listen the whole container of images
  document
    .querySelector(".sectionGameCardsContainer")
    .addEventListener("click", () => {
      // If game is not already current
      if (!store.isInGame) {
        // Start Timer
        setUpTimer("start");
        // Start the progress bar by injecting css classes
        let progressBar = document.getElementById("progressBarBackground");
        progressBar.classList.add("progressBarAnimate", "progressBarPlay");
        // And switch isInGame to true
        store.updateIsInGame(true);
      }
      // Else if already in Game, do nothing
    });
};
